export enum EVENTS {
  SEND_MESSAGE = "SEND_MESSAGE",
  MESSAGE = "MESSAGE",
  JOIN_ROOM = "JOIN_ROOM",
  CREATE_ROOM = "CREATE_ROOM",
  CONNECTED_TO_ROOM = "CONNECTED_TO_ROOM",
  USER_LEFT = "USER_LEFT",
  DM_LEFT = "DM_LEFT",
  DISCONNECTING = "disconnecting",
  UPDATE_CHARACTER = "UPDATE_CHARACTER",
  REFRESH_UI = "REFRESH_UI",
}
