export enum EVENTS {
  SEND_MESSAGE = "SEND_MESSAGE",
  MESSAGE = "MESSAGE",
  THROW_DICE = "THROW_DICE",
  JOIN_ROOM = "JOIN_ROOM",
  CREATE_ROOM = "CREATE_ROOM",
  DM_LEFT = "DM_LEFT",
  DISCONNECTING = "disconnecting",
  UPDATE_CHARACTER = "UPDATE_CHARACTER",
  REFRESH_ROOM = "REFRESH_ROOM",
}
