export enum EModals {
  JOIN_GAME = "JOIN_GAME",
  CREATE_GAME = "CREATE_GAME",
  CONFIRMATION = "CONFIRMATION",
  REGISTER = "REGISTER",
  LOGIN = "LOGIN",
  WIKI = "WIKI",
  PLAYER_LIST = "PLAYER_LIST",
  CHARACTER_CREATION = "CHARACTER_CREATION",
}
